### ISSUE TITLE
macOS install failed

### ISSUE THREAD

**Issue by evkumar71** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#10]
ERROR: Command errored out with exit status 1:
     command: /Users/username/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-install-q02vb52v/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-install-q02vb52v/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-install-q02vb52v/matplotlib/
    Complete output (107 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Traceback (most recent call last):
      File "/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/easy_install-w8z7ou_e/numpy-1.21.4/tools/cythonize.py", line 59, in process_pyx
        import Cython
    ModuleNotFoundError: No module named 'Cython'

**Comment by stefmolin** [comment]
Hi there,

It's hard to see what is going on with what you have included. Can you provide all the commands you ran and the full output?

**Comment by Sinansi** [comment]
In the last two lines, you are trying to import Cython but Cython is not found. Maybe you need to install Cython?

**Comment by evkumar71** [comment]
I was trying to create the python virtual environment. My machine (M1 chip) has macOS Monterey 12.0.1. and python ver# is 3.8.2. It seems to fail while installing matplotlib. I installed Cython as well and retired to reinstall all, but, again it fails with lot of error messages on screen.

**Comment by Sinansi** [comment]
Unless you need PyQT for building GUI, can you try installing only the basic version of matplotlib? 

The base version is now more popular than the full version because it has much less dependencies, yet you still get most of its features.

https://anaconda.org/conda-forge/matplotlib-base

**Comment by stefmolin** [comment]
@evkumar71 Please provide the exact commands you ran, so we can rule out any issue there. 

If you were using venv, then take a look at [this](https://stackoverflow.com/questions/66122146/pip-install-matplotlib-fails-on-m1-mac) or try with conda. If neither of those work, please provide all the messages you are seeing on the screen along with the exact commands you ran. You can use this to make a collapsible section in your response:

````
<details>
  <summary>Full output</summary>

   ```
   **Paste the full output here**
   ```
</details>
````

**Comment by evkumar71** [comment]
Hi Stefanie,

I was able to install Matplotlib after a few attempts - "pip install matplotlib". 
I am finding it a bit hard to copy & paste the entire log.

I executed "pip install scipy" and I see it is erroring out after some time - log output is pasted below.

ERROR: Command errored out with exit status 1:
   command: /Users/usrname/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/bin/python3 /private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-standalone-pip-wf3o9ky0/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-build-env-z73fqy5r/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.18' 'numpy==1.14.5; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.4.3'
       cwd: None
  Complete output (4807 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Collecting wheel
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting setuptools
    Downloading setuptools-58.5.3-py3-none-any.whl (946 kB)
  Collecting Cython>=0.29.18
    Using cached Cython-0.29.24-py2.py3-none-any.whl (979 kB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3.zip (6.4 MB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting pybind11>=2.4.3
    Using cached pybind11-2.8.1-py2.py3-none-any.whl (208 kB)
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-install-jylsi33j/numpy_c4be5f5ad66b4b24a62b1f90a548b55d/setup.py'"'"'; __file__='"'"'/private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-install-jylsi33j/numpy_c4be5f5ad66b4b24a62b1f90a548b55d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-wheel-j_67uzbi
         cwd: /private/var/folders/tc/c8rjp8hn765724hng7xbcs5h0000gn/T/pip-install-jylsi33j/numpy_c4be5f5ad66b4b24a62b1f90a548b55d/
    Complete output (4419 lines):
    Running from numpy source directory.
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    blis_info:
    customize UnixCCompiler
      libraries blis not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    openblas_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries tatlas not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_3_10_blas_info:
    customize UnixCCompiler
      libraries satlas not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_blas_info:
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    accelerate_info:
    customize UnixCCompiler
      libraries accelerate not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
    Library accelerate was not found. Ignoring
    customize UnixCCompiler
      libraries veclib not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
    Library veclib was not found. Ignoring
      FOUND:
        extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  
      FOUND:
        extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  
    /bin/sh: svnversion: command not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    flame_info:
    customize UnixCCompiler
      libraries flame not found in ['/Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
  
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
  
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
  
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /Users/vijay/learn_pandas/Hands-On-Data-Analysis-with-Pandas-2nd-edition/book_env/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
  
      FOUND:
        extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  
    /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running bdist_wheel
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-10.14.6-arm64-3.8
    creating build/src.macosx-10.14.6-arm64-3.8/numpy
    creating build/src.macosx-10.14.6-arm64-3.8/numpy/distutils
    building library "npymath" sources
    get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize NAGFCompiler
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize IBMFCompiler
    Could not locate executable xlf90
    Could not locate executable xlf
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    don't know how to compile Fortran code on platform 'posix'
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration

**Comment by stefmolin** [comment]
@evkumar71  I updated your response to use the collapsible section.

Can you please tell me **all** the commands you have run &ndash; not just the current one? At this point I don't know what you have done or how you did it. It's possible you've gotten yourself into a state from which it is better to start over from scratch.

**Comment by evkumar71** [comment]
I upgraded pip ver on my machine to 21.3.1 and was following the commands in ch-1 :-

"source book_env/bin/activate"
"pip3 install -r requirements.txt". 

Since it wasn't working, I was installing packages one after another as given below :
pip install grapviz
pip install jupyterlab
pip install matplotlib
etc..

I was able to install most of the packages listed in "requirements.txt" except the following :-

scikit-learn
imbalanced-learn
scipy
seaboard
statsmodels

It is falling for those.

**Comment by stefmolin** [comment]
It sounds like there are some non-Python dependencies that are causing all the issues. When you install with `pip`, it doesn't take care of those, meaning you have to track down each of those and install it yourself. I would recommend that you switch to conda, which will handle all of that for you.
