### ISSUE TITLE
./visual-aids

### ISSUE THREAD

**Issue by devil-is-a-part-timer** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#11]
Hi,
It seems I can not install ./visual-aids
I deleted the 18th line from file and all the libraries from requirements.txt file were installed.
I tried to google but can not find any info on how to install it separately.
Can you please help me with the 18th line - ./visual-aids installation?

![image](https://user-images.githubusercontent.com/96849485/148324628-5cac5c6e-0207-4d2a-b254-994c5be068d5.png)
![image](https://user-images.githubusercontent.com/96849485/148324824-039fbbc8-1e0a-4d9d-aa54-933b93cac88a.png)

Thank you!

**Comment by stefmolin** [comment]
Hi there. From your command line screenshot, I can see that you aren't in the directory containing the files for this repo. The `visual-aids` package is in this repo, so if you aren't in that directory when you run the command you are running it `pip` won't be able to find it.

Depending on where you cloned/downloaded this repo, your path will be different. Assuming you did so from the directory you are running the `pip` command from, you can change to the correct directory with the following command (more info on page 35 in the book &ndash; from the tip box to the bottom of the page):

```shell
cd Hands-On-Data-Analysis-with-Pandas-2nd-edition
```

This folder should also have the `requirements.txt` file (unless you moved it, in which case you should move it back).

**Comment by devil-is-a-part-timer** [comment]
Hey Stefanie, thank you! You are right. I placed the visual aids folder in the repo to that path on my computer and it worked!
Once again, thank you :)
