### ISSUE TITLE
How to install stock_analysis package?

### ISSUE THREAD

**Issue by KisikChang** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#12]
Dear

I don't know how to install stock_analysis packate.
Please let me know to do.

Thanks
Kisik

**Comment by stefmolin** [comment]
Hi there. You will need to follow the instructions laid out in the book starting on page 34. Without any information from your end, I can't help more than that.

**Comment by KisikChang** [comment]
Dear Stefmolin,

I followed your instruction and I've learned your code until 'Adding reference lines' section in Chapter 6.


`from stock_analysis import stock_analyzer`
`fb_analyzer = StockAnalyzer(fb)`


The above second code in 3-customizing_visualizations.ipynb notebook makes an error as follows:

`---------------------------------------------------------------------------`
`ModuleNotFoundError                       Traceback (most recent call last)`
`~\AppData\Local\Temp/ipykernel_29928/2916400064.py in <module>`
`----> 1 from stock_analysis import stock_analyzer`
`      2 `
`      3 fb_analyzer = StockAnalyzer(fb)`
` `
`ModuleNotFoundError: No module named 'stock_analysis'`

I copied the 'visual_aids' folder into 'ch_06' folder and renamed as 'stock_analysis'.
The cell still shows the error.

What should I do?

**Comment by stefmolin** [comment]
> I copied the 'visual_aids' folder into 'ch_06' folder and renamed as 'stock_analysis'.

Why? These are two separate packages. In addition, there is no need to move anything when the directions for environment setup in chapter 1 are followed. I would suggest you go back to chapter 1 (page 34) and work through setting up the environment following the directions exactly or, alternatively, use [this](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) Binder environment, which has everything installed and therefore requires no setup on your end. If you chose the former and have issues along the way, please provide all commands you have run from the command line and their output.

**Comment by KisikChang** [comment]
I solved the problem after re-install the requirements files.

Thanks
