### ISSUE TITLE
pip is configured with locations that require TLS/SSL; Cannot find command 'git' - do you have 'git' installed and in your PATH?

### ISSUE THREAD

**Issue by iracildols** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#14]
### Required attestation
- [x] I have **completely and exactly** followed the virtual environment setup instructions from the book or [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) in absence of the book.
- [x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [x] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
Windows 11, Version 21H2, Build 22000.438;

##### 2. Which Python version are you using?
Anaconda3 with Python 3.9.7

##### 3. Are you using `conda` or `venv`?
conda

---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:

<details>

```
TODO: paste commands and any traceback here
```

</details>

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.

---

My systemis giving two error messages:
- First: "WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available."
- Second: "ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/stefmolin/login-attempt-simulator.git 'C:\Users\iraci\AppData\Local\Temp\pip-req-build-1mj3iakt'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?"
My operating System is Windows 11, Version 21H2, Build 22000.438;
Anaconda3 with Python 3.9.7

Regards
Iracildo

**Comment by stefmolin** [comment]
@iracildols - It looks like you entered a bug report when you should have created a troubleshooting issue. Please take a look at the pinned issues as [this](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues/3) one is probably the same issue you are experiencing.

If that doesn't fix your issue, please open a **troubleshooting** issue and fill out all the information requested.

**Comment by stefmolin** [comment]
@iracildols - You will have to attach any screenshots directly in GitHub.

I converted your issue into a troubleshooting issue. Please go through the checklist at the top of this issue and mark the ones you completed. If you still have issues after that, fill in everything preceded with `TODO`: I already filled in the operating system and Python version for you, but I need you to do the rest.

![image](https://user-images.githubusercontent.com/24376333/151368558-8048119b-fe99-4d1f-93da-0aae686f4b14.png)

**Comment by iracildols** [comment]
3. I am using conda.

I troubleshooted my system and the issue now is as follows:

![image](https://user-images.githubusercontent.com/98404316/151478088-dd22b053-96c8-4b9c-a8be-0d582aaf9bc5.png)

4. ERROR: Invalid requirement: './visual-aids' (from line 18 of c:\Users\iraci\anaconda3\envs\book_env\Hands-On-Data-Analysis-with-Pandas-2nd-edition\requirements.txt)

5. The message above says there is an error in file requirements.txt at line 18.

Regards
Iracildo

**Comment by stefmolin** [comment]
@iracildols - Just confirming that you closed the issue because you got it working.

If not, you are almost there &ndash; you just need to change directories before running the `pip3 install` command:

```
cd Hands-On-Data-Analysis-with-Pandas-2nd-edition
pip3 install -r requirements.txt
```

**Comment by iracildols** [comment]
@stefmolin

I did what you suggested. I ran pip3 again. Follows messages of its execution.

The following part worked as expected.

[Execution_Messages.pdf](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/files/7958649/Execution_Messages.pdf)

This next part worked with errors.

[Error_Messaages.pdf](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/files/7958652/Error_Messaages.pdf)

The problem begins with: "Preparing wheel metadata ... error".

Please, tell me what to do!

Regards
Iracildo

**Comment by stefmolin** [comment]
@iracildols You set up your conda environment with a version of Python that is too recent for the NumPy requirement. This is the same as [this](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues/2) issue.

You will need to delete your conda virtual environment and this time specify the Python version when you create it:

```
conda remove --name book_env --all
conda create --name book_env python=3.8
```

It kind of looked like you cloned the repository into the folder for your virtual environment, which means it will likely be deleted. You should clone the repository elsewhere; for example, `c:\Users\iraci` would be a perfect spot for it. Then, as before, you would run through the install:

```
cd Hands-On-Data-Analysis-with-Pandas-2nd-edition
pip3 install -r requirements.txt
```

If you aren't comfortable with the command line, I would highly recommend you try the [Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster), which is all accessible through the web and doesn't require you to install anything locally.

**Comment by iracildols** [comment]
@stefmolin

Everything worked fine! Thanks for your help!

Best wishes
Iracildo
