### ISSUE TITLE
Missing Windows Tail Command in Notebook

### ISSUE THREAD

**Issue by NickFitz1812** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#17]
In Chapter 2, 2-creating_dataframes.ipynb, alternative windows commands are offered to open the csv and check the head lines. There is no alternative code for checking the tail of the document. Could this be included? There seems to be no small solution online similar to the head alternative.
 
![image](https://user-images.githubusercontent.com/86633852/163329250-24a1f477-0466-4b94-9d16-df4923ff5dd2.png)

**Comment by stefmolin** [comment]
The best solution in general would be to use [Cygwin](https://www.cygwin.com) or [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/about). This will give you access to `head`, `tail`, etc. I added the following Python alternative, which you can use to read the last line only:

```python
import os

with open('data/earthquakes.csv', 'rb') as file:
    file.seek(0, os.SEEK_END)
    while file.read(1) != b'\n':
        file.seek(-2, os.SEEK_CUR)
    print(file.readline().decode())
```

If you want to read in more than one line from the end, you can use the code below; however, note that it is actually reading the whole file, so definitely look into Cygwin/WSL:
```python
n = 2
with open('data/earthquakes.csv', 'r') as file:
    print('\r'.join(file.readlines()[-n:]))
```
