### ISSUE TITLE
issue with the requirements.txt file - ./visual-aids line

### ISSUE THREAD

**Issue by amonteromendez** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#18]
### Required attestation
- [X] I have **completely and exactly** followed the virtual environment setup instructions from the book or [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) in absence of the book.
- [X] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [X] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [X] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
Windows 10

##### 2. Which Python version are you using?
3.8

##### 3. Are you using `conda` or `venv`?
conda

---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:

<details>

```
I was able to successfully create and activate the environment by using the following statements:
conda create --name book_env python=3.8
conda activate book_env

When I tried to run the packages setup command I got the following error message (please see screenshot below).

After removing the **./visual-aids** line from the requirements file the setup completed successfully.

Any inputs on why this failed or how can it be fixed?


Please let me know if you need me to provide additonal information
![error(1)](https://user-images.githubusercontent.com/83610408/169359695-e69cb085-26da-4abb-8ebd-49292c6f7b6f.jpg)
.

**Comment by amonteromendez** [comment]
![error(1)](https://user-images.githubusercontent.com/83610408/169359282-80314dbe-27d2-4b38-939f-c806eb75b587.jpg)

Adding screenshot of error message.

**Comment by JaviCampoy** [comment]
Hi amonteromendez,
Same here. Did you manager to solve it?
Cheers,
Javie
![InvalidRequest](https://user-images.githubusercontent.com/96846603/184515665-7e1a47db-5444-4483-9d45-0426057768c0.PNG)
r

**Comment by stefmolin** [comment]
@JaviCampoy - you are not running the command from the proper folder. You need to first `cd` into the book repo as mentioned in the instructions.

**Comment by JaviCampoy** [comment]
Hi stefmolin,

My bad! I´m very new to this and assumed that it was "only" needed when not using conda. I moved to the cloned repo folder and looks good.

Thanks!
