### ISSUE TITLE
introduction_to_data_analysis.ipynb - ImportError: cannot import name '_centered' from 'scipy.signal.signaltools'

### ISSUE THREAD

**Issue by EagerBeaver212** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#20]
### Required attestation
- [x] I am using a virtual environment that matches the book specifications **exactly**.
- [x] I confirm that my fork is up to date with the latest changes in this repository.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue).
- [x] I have confirmed that my results match those obtained when running the code using [this](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) Binder environment.

---

##### 1. Which OS are you using?

Windows 10 - 7th Gen Intel chip

##### 2. Which Python version are you using?

Python 3.8.13

##### 3. Are you using `conda` or `venv`?

conda

##### 4. Package versions

# Name                    Version                   Build  Channel
anyio                     3.6.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
babel                     2.10.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.0                    pypi_0    pypi
ca-certificates           2022.4.26            haa95532_0    anaconda
certifi                   2021.10.8        py38haa95532_2    anaconda
cffi                      1.15.0                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 0.8.3                    pypi_0    pypi
fastjsonschema            2.15.3                   pypi_0    pypi
git                       2.34.1               haa95532_0    anaconda
idna                      2.10                     pypi_0    pypi
imbalanced-learn          0.7.0                    pypi_0    pypi
importlib-metadata        4.11.4                   pypi_0    pypi
importlib-resources       5.7.1                    pypi_0    pypi
ipykernel                 6.13.0                   pypi_0    pypi
ipympl                    0.6.2                    pypi_0    pypi
ipython                   8.4.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
json5                     0.9.8                    pypi_0    pypi
jsonschema                4.5.1                    pypi_0    pypi
jupyter-client            7.3.1                    pypi_0    pypi
jupyter-core              4.10.0                   pypi_0    pypi
jupyter-server            1.17.0                   pypi_0    pypi
jupyterlab                3.0.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.14.0                   pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
login-attempt-simulator   0.2                      pypi_0    pypi
lxml                      4.9.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.3.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
ml-utils                  0.2.0                    pypi_0    pypi
mplfinance                0.12.9b1                 pypi_0    pypi
nbclassic                 0.3.7                    pypi_0    pypi
nbclient                  0.6.4                    pypi_0    pypi
nbconvert                 6.5.0                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
nest-asyncio              1.5.5                    pypi_0    pypi
notebook                  6.4.11                   pypi_0    pypi
notebook-shim             0.1.0                    pypi_0    pypi
numpy                     1.19.4                   pypi_0    pypi
openssl                   1.1.1n               h2bbff1b_0    anaconda
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.0                    pypi_0    pypi
pandas-datareader         0.10.0                   pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.1.1                    pypi_0    pypi
pip                       21.2.2           py38haa95532_0
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.8.13               h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
python-graphviz           0.14.1                   pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pywinpty                  2.0.5                    pypi_0    pypi
pyzmq                     23.0.0                   pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
seaborn                   0.11.0                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                61.2.0           py38haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlalchemy                1.3.20                   pypi_0    pypi
sqlite                    3.38.3               h2bbff1b_0
stack-data                0.2.0                    pypi_0    pypi
statsmodels               0.12.1                   pypi_0    pypi
stock-analysis            0.2                      pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.2.2.post1              pypi_0    pypi
urllib3                   1.25.11                  pypi_0    pypi
vc                        14.2                 h21ff451_1
visual-aids               2.0                      pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.3.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.6.0                    pypi_0    pypi
wincertstore              0.2              py38haa95532_2
zipp                      3.8.0                    pypi_0    pypi

##### 5. Run the `ch_01/checking_your_setup.ipynb` notebook
Screenshot after running the `ch_01/checking_your_setup.ipynb` notebook:

![image](https://user-images.githubusercontent.com/83063651/171460874-bb3607ee-0a68-469e-84ae-715c119eb836.png)

### Commands run and their outputs

Setup
from visual_aids import stats_viz
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from visual_aids import stats_viz

File ~\anaconda3\envs\book_env\lib\site-packages\visual_aids\stats_viz.py:13, in <module>
     11 from sklearn.metrics import r2_score
     12 from statsmodels.distributions.empirical_distribution import ECDF
---> 13 from statsmodels.tsa.seasonal import seasonal_decompose
     15 def _non_symmetric_data():
     16     """Generate non-symmetric data for plots"""

File ~\anaconda3\envs\book_env\lib\site-packages\statsmodels\tsa\seasonal.py:12, in <module>
     10 from statsmodels.tools.validation import PandasWrapper, array_like
     11 from statsmodels.tsa._stl import STL
---> 12 from statsmodels.tsa.filters.filtertools import convolution_filter
     13 from statsmodels.tsa.tsatools import freq_to_period
     15 __all__ = ['STL', 'seasonal_decompose', 'seasonal_mean', 'DecomposeResult']

File ~\anaconda3\envs\book_env\lib\site-packages\statsmodels\tsa\filters\filtertools.py:18, in <module>
     16 import scipy.fftpack as fft
     17 from scipy import signal
---> 18 from scipy.signal.signaltools import _centered as trim_centered
     20 from statsmodels.tools.validation import array_like, PandasWrapper
     22 def _pad_nans(x, head=None, tail=None):

ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (C:\Users\gregc\anaconda3\envs\book_env\lib\site-packages\scipy\signal\signaltools.py)

**Comment by stefmolin** [comment]
Hi there. It looks like the latest version of `scipy` isn't compatible and will need to be downgraded. I updated the repo, so you will need to pull the changes and try again.

**Comment by EagerBeaver212** [comment]
Thank you - issue resolved!
