### ISSUE TITLE
Error installing requirements.txt

### ISSUE THREAD

**Issue by gpiero-asc** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#21]
I tried several times even on different Linux distribution, but I cannot complete the installation.
I include two error messages. The first with the default version of pip, and the second after upgrading it, though the error message says it's not a pip issue.

[error.txt](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/files/8934931/error.txt)
[error2.txt](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/files/8934932/error2.txt)
.

**Comment by stefmolin** [comment]
Hi there,

Not much to go on here, but it looks like you are using Python 3.10, which doesn't seem to be compatible with the version of NumPy required. I would suggest you try using Python 3.9, which is confirmed to work on Linux (see the [Binder](https://mybinder.org/v2/gh/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/master?urlpath=lab) for this repo). If that doesn't work and you don't want to try with `conda`, then please provide all the information that is requested of a [troubleshooting issue](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues/new?assignees=&labels=troubleshooting&template=1---troubleshoot-installation-issues.md&title=) (you can copy and paste what that generates and then fill it in here as a new comment).

**Comment by apaksoy** [comment]
I have had the same problem and got a similar error message when installing the required external libraries in a virtual environment on macOS Monterey with Python 3.10.x. After seeing the owner's comment here, I also installed Python 3.9.13 and the problem was resolved.

**Comment by gpiero-asc** [comment]
I dropped the book repository. I'm no more interested in it.
