### ISSUE TITLE
No such File or Directory

### ISSUE THREAD

**Issue by dscretching** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#25]
### Required attestation
- [x] I have **completely and exactly** followed the virtual environment setup instructions from the book or [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) in absence of the book.
- [x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [x] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---
This could be an obvious mistake so I apologize for any wasted time.

##### 1. Which OS are you using?
TODO: Provide your OS here &ndash; make sure to differentiate between Intel and M1 chip Macs.
Mac (2017) OS Ventura 13.0.1 Intel Iris

##### 2. Which Python version are you using?
Most recent:  python 3.11.0

##### 3. Are you using `conda` or `venv`?
I am using venv
---

### Commands run and their outputs
book_env) Desis-MacBook-Pro:Hands-On-Data-Analysis-with-Pandas-2nd-edition-master dscretching$ pip3 install -r requirements.txt
bash: /Users/dscretching/Desktop/Python/book_env/bin/pip3: **No such file or directory**

(book_env) Desis-MacBook-Pro:Hands-On-Data-Analysis-with-Pandas-2nd-edition-master dscretching$ pip3 install -r '/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/requirements.txt'
bash: /Users/dscretching/Desktop/Python/book_env/bin/pip3: **No such file or directory**

<details>

```
TODO: paste commands and any traceback here
```

</details>

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.

**Comment by dscretching** [comment]
I found a person with the same issue under issues

**Comment by dscretching** [comment]
After updating my python for 3.11.1 I now have an error output that looks like this:

(book_env) Desis-MacBook-Pro:Hands-On-Data-Analysis-with-Pandas-2nd-edition-master dscretching$ pip3 install -r requirements.txt
Collecting git+https://github.com/stefmolin/login-attempt-simulator.git@2nd_edition (from -r requirements.txt (line 15))
  Cloning https://github.com/stefmolin/login-attempt-simulator.git (to revision 2nd_edition) to /private/var/folders/90/ph3222hj7kg6qpkf3d5z613c0000gn/T/pip-req-build-w5kmrnf1
  error: subprocess-exited-with-error
  
  × git version did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git version did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by dscretching** [comment]
I've tried copying the pathname to receive this output:


(book_env) Desis-MacBook-Pro:Hands-On-Data-Analysis-with-Pandas-2nd-edition-master dscretching$ pip3 install -r '/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/requirements.txt'
Traceback (most recent call last):
  File "/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/book_env/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/book_env/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/book_env/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/book_env/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/Users/dscretching/Desktop/Python/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/book_env/lib/python3.11/site-packages/pip/_internal/build_env.py", line 15, in <module>
    from pip._vendor.certifi import where
ImportError: cannot import name 'where' from 'pip._vendor.certifi' (unknown location)

**Comment by dscretching** [comment]
I reinstalled git via homebrew and all problems were solved but now when I get to scikit-learn in the requirements package everything stops with an error. 

I tried installing it individually and I received this output:

Collecting scikit-learn==0.23.2
  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1

**Comment by stefmolin** [comment]
@dscretching - My guess is that the Python version is too high. Try with Python 3.8 or 3.9.

**Comment by dscretching** [comment]
I have tried python 3.8 and received this error. Its looking much better than before though!

ERROR: Cannot install -r requirements.txt (line 18) and stock-analysis 0.2 (from git+https://github.com/stefmolin/stock-analysis.git) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested stock-analysis 0.2 (from git+https://github.com/stefmolin/stock-analysis.git)
    visual-aids 2.0 depends on stock-analysis 0.2 (from git+https://github.com/stefmolin/stock-analysis.git@2nd_edition)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by dscretching** [comment]
I redownloaded the requirements file and It was a success!
