### ISSUE TITLE
wheel installation issue

### ISSUE THREAD

**Issue by miirsadra** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#27]
### Required attestation
- [x] I have **completely and exactly** followed the virtual environment setup instructions from the book or [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) in absence of the book.
- [x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [x] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
M1 Pro Ventura

##### 2. Which Python version are you using?
3.11.1
##### 3. Are you using `conda` or `venv`?
conda

---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:

        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [67 lines of output]
            The Meson build system
            Version: 0.62.2
            Source dir: /private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4
            Build dir: /private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4/.mesonpy-gjey8zge/build
            Build type: native build
            Project name: SciPy
            Project version: 1.9.1
            C compiler for the host machine: cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
            C linker for the host machine: cc ld64 820.1
            C++ compiler for the host machine: c++ (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
            C++ linker for the host machine: c++ ld64 820.1
            Host machine cpu family: aarch64
            Host machine cpu: arm64
            Compiler for C supports arguments -Wno-unused-but-set-variable: YES
            Library m found: YES
      
            ../../meson.build:41:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
            The following exception(s) were encountered:
            Running "gfortran --version" gave "[Errno 2] No such file or directory: 'gfortran'"
            Running "gfortran -V" gave "[Errno 2] No such file or directory: 'gfortran'"
            Running "flang --version" gave "[Errno 2] No such file or directory: 'flang'"
            Running "flang -V" gave "[Errno 2] No such file or directory: 'flang'"
            Running "nvfortran --version" gave "[Errno 2] No such file or directory: 'nvfortran'"
            Running "nvfortran -V" gave "[Errno 2] No such file or directory: 'nvfortran'"
            Running "pgfortran --version" gave "[Errno 2] No such file or directory: 'pgfortran'"
            Running "pgfortran -V" gave "[Errno 2] No such file or directory: 'pgfortran'"
            Running "ifort --version" gave "[Errno 2] No such file or directory: 'ifort'"
            Running "ifort -V" gave "[Errno 2] No such file or directory: 'ifort'"
            Running "g95 --version" gave "[Errno 2] No such file or directory: 'g95'"
            Running "g95 -V" gave "[Errno 2] No such file or directory: 'g95'"
      
            A full log can be found at /private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4/.mesonpy-gjey8zge/build/meson-logs/meson-log.txt
            + meson setup --native-file=/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/Library/Frameworks/Python.framework/Versions/3.11 /private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4 /private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4/.mesonpy-gjey8zge/build
            Traceback (most recent call last):
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
                main()
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
                return hook(config_settings)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
                with _project(config_settings) as project:
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
                return next(self.gen)
                       ^^^^^^^^^^^^^^
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 948, in _project
                with Project.with_temp_working_dir(
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
                return next(self.gen)
                       ^^^^^^^^^^^^^^
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
                yield cls(source_dir, tmpdir, build_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 682, in __init__
                self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 713, in _configure
                self._meson(
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 696, in _meson
                return self._proc('meson', *args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-build-env-_v7xpwn_/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 691, in _proc
                subprocess.check_call(list(args))
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
                raise CalledProcessError(retcode, cmd)
            subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/Library/Frameworks/Python.framework/Versions/3.11', '/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4', '/private/var/folders/ss/1c56194x3g72fv7f14_pftfc0000gn/T/pip-install-x6ns8xbu/scipy_629eab5391024ff1a1c9347607f3b5b4/.mesonpy-gjey8zge/build']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Note that I used pip3 install -r requirements.txt because in case of conda install, -r is not defined. 

* The book is great. thank you!

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.
<img width="1902" alt="Screenshot 2023-01-06 at 17 04 03" src="https://user-images.githubusercontent.com/120222556/211050393-f4bf7341-cd46-4055-a62a-b1bc0ba1b308.png">

**Comment by stefmolin** [comment]
@miirsadra - The version of Python you are using is likely way to too high because it is trying to install a version of `scipy` that is outside of the bounds listed in the requirements. In addition, there was recently an upstream packaging issue that affects Apple Silicon users. Please follow the installation instructions in the README for [Apple Silicon Users](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#apple-silicon-users). Make sure you pull the latest changes though, or you won't have the file needed to run those commands.

**Comment by miirsadra** [comment]
@stefmolin First of all I'd like you thanks for replying me back. As you might know Apple has it's own python version as well. 
I think I fixed it somehow without conda. It only makes me confuse!
