### ISSUE TITLE
Problem installing GitHub packages: "Cannot find command 'git' - do you have 'git' installed and in your PATH?"

### ISSUE THREAD

**Issue by TsvetalinGr** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#3]
Hi I have problems with setting up the book_env. 

(book_env) C:\Users\TGrigorov>pip3 install -r %cd%\Documents\Python\Packt\Hands-On-Data-Analysis-with-Pandas-2nd-edition-master\requirements.txt
Collecting git+https://github.com/stefmolin/login-attempt-simulator.git@2nd_edition (from -r C:\Users\TGrigorov\Documents\Python\Packt\Hands-On-Data-Analysis-with-Pandas-2nd-edition-master\requirements.txt (line 15))
  Cloning https://github.com/stefmolin/login-attempt-simulator.git (to revision 2nd_edition) to c:\users\tgrigorov\appdata\local\temp\pip-req-build-zgwb1xxn
  Running command git clone -q https://github.com/stefmolin/login-attempt-simulator.git 'C:\Users\TGrigorov\AppData\Local\Temp\pip-req-build-zgwb1xxn'
  ERROR: Error [WinError 2] Das System kann die angegebene Datei nicht finden while executing command git clone -q https://github.com/stefmolin/login-attempt-simulator.git 'C:\Users\TGrigorov\AppData\Local\Temp\pip-req-build-zgwb1xxn'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

I managed to install evrything till "wheel". But "login-attempt-simulator", "ml-utils", "stock-analysis" and "visual-aids" are not installed.

**Comment by stefmolin** [comment]
Hi @TsvetalinGr,

The error message is telling you that `pip` doesn't know where you have installed `git`. Can you confirm that you have `git` installed? It can be installed for Windows [here](https://git-scm.com/download/win).

**Comment by tompearce** [comment]
(book_env) C:\Users\tompe\my_folder>pip3 install -r requirements.txt
Collecting git+https://github.com/stefmolin/login-attempt-simulator.git@2nd_edition (from -r requirements.txt (line 15))
  Cloning https://github.com/stefmolin/login-attempt-simulator.git (to revision 2nd_edition) to c:\users\tompe\appdata\local\temp\pip-req-build-vc8wlanj
  Running command git clone -q https://github.com/stefmolin/login-attempt-simulator.git 'C:\Users\tompe\AppData\Local\Temp\pip-req-build-vc8wlanj'
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/stefmolin/login-attempt-simulator.git 'C:\Users\tompe\AppData\Local\Temp\pip-req-build-vc8wlanj'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Hi Stef

I am getting the same error. I have git installed but how do I let pip know where it is?**

**Comment by stefmolin** [comment]
@tompearce - you need to add it to the PATH environment variable. Currently, `pip` is checking for `git.exe` in all the locations listed in PATH, but the location for the `git` executable is not there. I believe during installation of `git` you have the option to update PATH automatically, but you can do it at any time: find the filepath to `git.exe` on your local machine (for example, `C:\Windows\...\git\bin`) and then add it to PATH ([instructions here](https://www.computerhope.com/issues/ch000549.htm)).

**Comment by tompearce** [comment]
@stefmolin -Great thanks. PATH updated and now all installed fine.

**Comment by stefmolin** [comment]
@TsvetalinGr - Were you able to resolve your issue?
