### ISSUE TITLE
Errors in running finacial_analysis.ipynb in chapter 7

### ISSUE THREAD

**Issue by lxlofpku** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#33]
### Required attestation
- [Y] I have **completely and exactly** followed the virtual environment setup instructions from the book and have consulted the [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) for any updates.
- [Y] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [Y] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [Y] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
TODO: Provide your OS here &ndash; make sure to differentiate between Intel and M1 chip Macs.

Mac M2

##### 2. Which Python version are you using?
TODO: Provide your Python version here.

Python 3.8

##### 3. Are you using `conda` or `venv`?
TODO: Indicate whether you are using `conda` or `venv`.

conda

---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:

Hi Stefanie:

Recently I installed the stock-analysis package following the instruction in chapter 7 (p. 395) of your book. That is, I installed it by running (in book_env environment):

1. git clone git@github.com:stefmolin/stock-analysis.git
2. pip3 install -r stock-analysis/requirements.txt
3. pip3 install -e stock-analysis

All went through smoothly, indicating that the installation was successful.

However, as I run the finacial-analysis.ipynb notebook, I could not get the data. The problem is described in the attached screen shots. I have read through the trace back but cannot get a clue what is wrong. 

Best regards,
Li-Xin

<details>

The problem is displayed in the the screen shots displaced below.

```
TODO: paste commands and any traceback here
```

</details>

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.
![cap1](https://user-images.githubusercontent.com/115785359/213913754-aa1e7f62-cc5d-4f51-8878-db329c80916e.jpg)
![cap2](https://user-images.githubusercontent.com/115785359/213913769-a89d4095-ecf3-4943-9f40-da3ff592d3d5.jpg)

**Comment by stefmolin** [comment]
The `stock_analysis` library is using the `pandas_datareader` library to query the Yahoo! Finance API for the information. The API has recently changed, which is causing the [issue](https://github.com/pydata/pandas-datareader/issues/952) since the `pandas_datareader` library doesn't yet know how to handle it. Upstream changes like this are expected, which is why I included all the datasets for this chapter in the `data/` folder — use the note box right before "The Stock reader class" section in the book for a code snippet to read them in: 

```
pd.read_csv('data/...', index_col='date', parse_dates=True)
```

**Comment by lxlofpku** [comment]
> The `stock_analysis` library is using the `pandas_datareader` library to query the Yahoo! Finance API for the information. The API has recently changed, which is causing the [issue](https://github.com/pydata/pandas-datareader/issues/952) since the `pandas_datareader` library doesn't yet know how to handle it. Upstream changes like this are expected, which is why I included all the datasets for this chapter in the `data/` folder — use the note box right before "The Stock reader class" section in the book for a code snippet to read them in:
> 
> ```
> pd.read_csv('data/...', index_col='date', parse_dates=True)
> ```

Hi Stefanie, I understand it now. Thanks a lot!
