### ISSUE TITLE
Visual Aids Install issue

### ISSUE THREAD

**Issue by baumstan** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#37]
(book_env) aarons-mbp:Hands-On-Data-Analysis-with-Pandas-2nd-edition kineret$ pip3 install visual-aids
ERROR: Could not find a version that satisfies the requirement visual-aids (from versions: none)
ERROR: No matching distribution found for visual-aids

**Comment by stefmolin** [comment]
Hi there. It looks like you aren't following the setup instructions. The `visual_aids` package is part of this repository, so you need to have the files on your machine locally and point pip to where you have it. It looks like you have the files locally, so you can try this, but the best would be to follow the instructions in chapter 1:

```shell
pip install ./visual-aids
```

**Comment by baumstan** [comment]
Thanks.
