### ISSUE TITLE
Problem with stock_analysis package

### ISSUE THREAD

**Issue by vhphan** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#43]
Hi,

This used to work!
 
But now I am getting error running the first cell in the notebook financial_analysis.ipynb.
I suspect this may be due to changes in Yahoo's API (?).

`
import stock_analysis

reader = stock_analysis.StockReader('2019-01-01', '2020-12-31')

# get faang data
fb, aapl, amzn, nflx, goog = (
    reader.get_ticker_data(ticker)
    for ticker in ['META', 'AAPL', 'AMZN', 'NFLX', 'GOOG']
)
`

Running the cell gives:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 6
      3 reader = stock_analysis.StockReader('2019-01-01', '2020-12-31')
      5 # get faang data
----> 6 fb, aapl, amzn, nflx, goog = (
      7     reader.get_ticker_data(ticker)
      8     for ticker in ['META', 'AAPL', 'AMZN', 'NFLX', 'GOOG']
      9 )
     11 # get S&P 500 data
     12 sp = reader.get_index_data('S&P 500')

Cell In[2], line 7, in (.0)
      3 reader = stock_analysis.StockReader('2019-01-01', '2020-12-31')
      5 # get faang data
      6 fb, aapl, amzn, nflx, goog = (
----> 7     reader.get_ticker_data(ticker)
      8     for ticker in ['META', 'AAPL', 'AMZN', 'NFLX', 'GOOG']
      9 )
     11 # get S&P 500 data
     12 sp = reader.get_index_data('S&P 500')

File [~/miniconda3/envs/book_env/lib/python3.8/site-packages/stock_analysis/utils.py:39](https://vscode-remote+ssh-002dremote-002b150-002e236-002e1-002e92.vscode-resource.vscode-cdn.net/home/netan-celcom-my/vhphan/books/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_07/~/miniconda3/envs/book_env/lib/python3.8/site-packages/stock_analysis/utils.py:39), in label_sanitizer..method_wrapper(self, *args, **kwargs)
     37 @wraps(method)
     38 def method_wrapper(self, *args, **kwargs):
...
--> 153     data = j["context"]["dispatcher"]["stores"]["HistoricalPriceStore"]
    154 except KeyError:
    155     msg = "No data fetched for symbol {} using {}"

TypeError: string indices must be integers

**Comment by stefmolin** [comment]
@vhphan - You are correct; this is due to an earlier change in the Yahoo! Finance API. I [fixed](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/pull/34) this a while back, but you will need to update your environment to get the fix. You can pull the changes to this repository and then reinstall.
