### ISSUE TITLE
Failures in running check_your_setup.ipynb

### ISSUE THREAD

**Issue by teddylee008** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#44]
### Required attestation
- [x] I have **completely and exactly** followed the virtual environment setup instructions from the book and have consulted the [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) for any updates.
- [x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [x] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
TODO: Provide your OS here &ndash; make sure to differentiate between Intel and M1 chip Macs.
Windows intel core i7 8th gen
##### 2. Which Python version are you using?
TODO: Provide your Python version here.
Ver 3.11.4
##### 3. Are you using `conda` or `venv`?
TODO: Indicate whether you are using `conda` or `venv`.
conda
---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:
Running check_your_setup.ipynb in kernel book_env in JupyterLab
<details>

```
TODO: paste commands and any traceback here
```
Using Python in D:\Anaconda3:
[FAIL] Python version >= 3.7.1 and < 3.10.0 is required, but 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)] is installed.

[FAIL] graphviz not installed.
[FAIL] imblearn not installed.
[FAIL] ipympl not installed.
[FAIL] jupyterlab version 3.0.4 is required, but 3.6.3 installed.
[FAIL] matplotlib version 3.3.2 is required, but 3.7.1 installed.
[FAIL] numpy version >= 1.19.2 and <= 1.19.5 is required, but 1.24.3 installed.
[FAIL] pandas version 1.2.0 is required, but 1.5.3 installed.
[FAIL] requests version 2.24.0 is required, but 2.31.0 installed.
[FAIL] sklearn version 0.23.2 is required, but 1.3.0 installed.
[FAIL] scipy version >= 1.5.0 and <= 1.7.3 is required, but 1.10.1 installed.
[FAIL] seaborn version >= 0.11.0 and <= 0.11.2 is required, but 0.12.2 installed.
[FAIL] sqlalchemy version >= 1.3.19 and <= 1.3.20 is required, but 1.4.39 installed.
[FAIL] statsmodels version >= 0.11.1 and <= 0.12.1 is required, but 0.14.0 installed.
[ OK ] wheel
[FAIL] login_attempt_simulator not installed.
[FAIL] ml_utils not installed.
[FAIL] stock_analysis not installed.
[FAIL] visual_aids not installed.

</details>

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.

**Comment by stefmolin** [comment]
Hi there &ndash; from the first line of your output, I can see that you aren't actually using the virtual environment that you should have created. It is using Python from your Anaconda installation, and therefore you won't have many of the requirements installed. See this line in your output?

```output
Using Python in D:\Anaconda3:
```

You will need to run `conda activate book_env` before you can open Jupyter and run this notebook. Then the line above will indicate that you are using the Python version in the virtual environment, which will be the correct one.

**Comment by teddylee008** [comment]
Hi Stefmolin, many thanks for your reply. Cheers
