### ISSUE TITLE
Ch 4 End of Chapter Exercise 10.4

### ISSUE THREAD

**Issue by christaplease** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#45]
I wanted to make sure I am understanding the logic of the question correctly. I took it that the question was asking for the first date a country had cases (excluding results from China). Looking at the solution, it states that Yemen's first case was on 4/10/20 but looking manually at the csv it has cases for Yemen on 01/06/20.

**Comment by stefmolin** [comment]
Hi there &ndash; I think you are getting tripped up by the date format. The `dateRep` column is in DD/MM/YY so the `01/06/20` value you are seeing is actually June 6th, while the solution is April 10th. This is why we process the `dateRep` string into a `date` column in part 1 of the exercise.

**Comment by christaplease** [comment]
Thank you for the assistance.
