### ISSUE TITLE
Problems with the online book at Packt

### ISSUE THREAD

**Issue by flyingdutch20** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#5]
Hi Stef,
Your book looks to have exactly the content that I was looking for but unfortunately I have some problems with your publisher.
I signed up for the trial of the online reader to see if your book indeed had the depth that I was looking for and I am pleased to tell you that it does. However when I came to Chapter 2; section Pandas Data Structures and subsequent sections, it appears that most of the sections are incomplete, cut off with an ellipsis.
But what annoys me even more of the publisher is that they advertise the pbook + ebook together as special offer for £33.99 so I clicked on that offer, which takes me to their shop where that offer cannot be honoured. You can order the pbook via Amazon for £30.99 or the ebook through Packt directly for £23.99. 
I am very happy to support writers by buying their books, but if the publishers make this big a mess of it then unfortunately you as an author are missing out. I have pointed the above out to the publishers through their support page but unfortunately they are not willing to honour what they advertise, they just tell me that is a mistake of the 'reader' application. But if you look now, that 'mistake' is still not corrected.
I have bought many books through Pragmatic Programmers and through Manning so I find it very sad that Packt can't deliver in the same way.
I sincerely hope that you will continue writing books as I find the book top-notch (from how far I've been able to read) but hope you will find a more supportive publisher.
Kind regards,
Ted

**Comment by abeer2696** [comment]
Hi,
I am reaching out to you on behalf of Packt. I will be requiring your email address to get in touch or you can reach out to me at abeerd@packt.com. We hope to solve your issue at the earliest possible.

Looking forward to your response.

Thanks!!

**Comment by flyingdutch20** [comment]
Hi abeerd@packt.com, I forwarded you the email conversation that I had with one of the support consultants from packt.
Kind regards,
Ted

**Comment by Mugerwa-joseph1789** [comment]
hey i got the book but at the start when i am trying to copy the files from github it fails...the link https://github.com/stefmolin/
Hands-On-Data-Analysis-with-Pandas-2nd-edition has refused to lead me to zip files...need help

**Comment by stefmolin** [comment]
Hi Ted,

Thank you for your support of my content &ndash; much appreciated. I hope Abeer was able to resolve your issues.

Best,
Stefanie

**Comment by Mugerwa-joseph1789** [comment]
yes
