### ISSUE TITLE
Help @Mugerwa-joseph1789 with setup

### ISSUE THREAD

**Issue by stefmolin** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#6]
@Mugerwa-joseph1789 - You commented on a few issues with some questions. I'm opening this for you to put your questions in a single thread:

> the requirements.txt is refusing to install some files starting from line 425 error catcher. the errors continue to other parts

Please respond with the traceback, so I can help you.

> how do i transfer my exercises to github?

I see that you have forked the repository, so first clone [your forked repository](https://github.com/Mugerwa-joseph1789/Hands-On-Data-Analysis-with-Pandas-2nd-edition) onto your local machine. Use that repository when you work through the book. To push your exercises up to GitHub, you will need to use `git` commands &ndash; see [this](https://www.freecodecamp.org/news/learn-the-basics-of-git-in-under-10-minutes-da548267cc91/) article for a quick introduction to `git` along with the commands you will need.

**Comment by Mugerwa-joseph1789** [comment]
thanks alot
