### ISSUE TITLE
Error installing venv packages

### ISSUE THREAD

**Issue by markdietrich1** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#7]
Hi Stefanie, I'm running python 3.8 within my venv and getting a similar "wheels" area error:

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\markd\book_env2\scripts\python.exe' 'c:\users\markd\book_env2\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\markd\AppData\Local\Temp\tmpb2bl6x1r'
         cwd: C:\Users\markd\AppData\Local\Temp\pip-install-ry6bol8m\scipy_e49de6a1f70d4cf7bd58266d53541aa4
    Complete output (182 lines):
```

**Comment by markdietrich1** [comment]
An update: turns out I wasn't running 3.8, but 3.9. I'm having trouble with the advice you gave in the other thread:

python3 - m venv book_env python=3.6.2

...just isn't working. I go into book_env and python -V returns 3.9. Ugh.

Any other way to specify the previous python version, or should we use virtualenv?

**Comment by markdietrich1** [comment]
Stefanie, I did try virtualenv, and got as far as here:

`Collecting numpy==1.19.2
  Using cached numpy-1.19.2-cp36-cp36m-win32.whl (10.9 MB)
ERROR: Could not find a version that satisfies the requirement pandas==1.2.0 (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
ERROR: No matching distribution found for pandas==1.2.0`

**Comment by markdietrich1** [comment]
Stefanie, nevermind. Somehow I just couldn't get Python 3.9 off my system, and `>python3` kept pointing to it. I did an install of 3.8.8 and saw that` >python` points to 3.8.8, so I was able to create using `>python -m venv book_env`. All the required packages also successfully installed. Whew!

**Comment by stefmolin** [comment]
I'm glad you were able to figure it out @markdietrich1! For reference, your attempt to create the virtual environment with a specific version of Python didn't work because those instructions were for `conda`; you would have had to install Anaconda/Miniconda and use `conda` to set up the virtual environment instead of `venv`: 

```python
conda create --name book_env python=3.8
```

Let me know if you have any more questions, or if we can close this issue.
